### ISSUE TITLE
#TODO

### ISSUE THREAD

**Issue by daite** [daite/angel#1]
- [x] availabe web site stats (error handling)
- [x] add more korea torrent web sites
- [x] network error handling
